import { environment } from "src/environments/environment";

export const apiURL = environment.apiUrl;
export const menuNavegacionRoutes = apiURL + '/menu-navegacion';
export const submenuRoute = apiURL + '/submenus';
export const zonasRoute = apiURL + '/zonas';
export const tipoPersonaRoute = apiURL + '/tipo-persona';
export const tipoEmpleadosRoute = apiURL + '/tipo-empleado';
export const unidadMedidaRoute = apiURL + '/unidad-medida';
export const categoriaRoute = apiURL + '/categorias';
export const productosRoute = apiURL + '/productos';
export const preciosRoute = apiURL + '/precios';
export const empleadosRoute = apiURL + '/empleados';
export const clientesRoute = apiURL + '/clientes';
export const multitablasRoute = apiURL + '/multitablas';
export const rolesRoute = apiURL + '/roles';
export const permisosRoute = apiURL + '/permisos';
export const usuariosRoute = apiURL + '/usuarios';
export const asignacionesRoute = apiURL + '/asignaciones';
export const detalleAsignacionRoute = apiURL + '/detalle-asignacion';
export const preventasRoute = apiURL + '/preventas';
export const seguridadRoute = apiURL + '/seguridad';
export const ReniecDniService = apiURL + '/reniec-sunat';
